name: wolfWORDS
description: by a barely functional human
future: true
footer-links:
  github: okwolf
  instagram: okwolfgang
  linkedin: okwolf
  twitter: okwolf
# disqus:
google_analytics: UA-27540993-2
permalink: /:slug
plugins:
  - jekyll-seo-tag
  - jekyll-feed
sass:
  style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
