name: wolfWORDS
description: by a barely functional human
future: true
author: Wolfgang Wedemeyer
twitter:
  username: okwolf
  card: summary
footer-links:
  github: okwolf
  instagram: okwolfgang
  linkedin: okwolf
  twitter: okwolf
# disqus:
google_analytics: UA-27540993-2
permalink: /:slug
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
sass:
  style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
